### ISSUE TITLE
使用CH582M USB枚举过不去

### ISSUE THREAD

**Issue by 50617546** [HaiMianBBao/CherryUSB-Daplink#1]
已经发现问题 是USB_NUM_BIDIR_ENDPOINTS太小 改成8即可

**Comment by HaiMianBBao** [comment]
谢谢你，我更新了usbdc文件去兼容ch571,ch572,ch573，所以默认端点是5个，但是我忘记更新项目下面的usb config文件了。

**Comment by 50617546** [comment]
您好，我这边在测试CH582M DAPLINK的时候 发现他下载完后不会自动reset单片机运行app，请问您那边也是这样吗？有什么解决方法吗？




咯咯咯&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HaiMianBBao/CherryUSB-Daplink"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月28日(星期五) 晚上6:01
***@***.***&gt;;
抄送:&nbsp;"咯咯咯 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [HaiMianBBao/CherryUSB-Daplink] 使用CH582M USB枚举过不去 (Issue #1)





 
谢谢你，我更新了usbdc文件去兼容ch571,ch572,ch573，所以默认端点是5个，但是我忘记更新项目下面的usb config文件了。

**Comment by HaiMianBBao** [comment]
你在哪个IDE上面调试呢？勾上类似于reset and run了吗？

**Comment by 50617546** [comment]
感谢您的回复！keil上调试 有勾选reset and run，但是没有连接reset线 想用软件复位来run app



&nbsp;


咯咯咯&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月10日(星期四) 中午11:44
收件人: ***@***.***&gt;; 
抄送: "咯咯咯 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HaiMianBBao/CherryUSB-Daplink] 使用CH582M USB枚举过不去 (Issue #1)





 
你在哪个IDE上面调试呢？勾上类似于reset and run了吗？

**Comment by HaiMianBBao** [comment]
不客气，你加我qq吧1570139720
